"""initial schema

Revision ID: fb50d024ea2b
Revises:
Create Date: 2026-03-04 14:06:13.374005+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb50d024ea2b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("dataset_code", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column(
            "extraction_status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "SKIPPED",
                name="extractionstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("prefect_flow_run_id", sa.String(length=36), nullable=True),
        sa.Column("rows_extracted", sa.Integer(), nullable=True),
        sa.Column("rows_loaded", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(), nullable=True),
        sa.Column("loaded_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_metadata")),
    )
    op.create_table(
        "geo_lookup",
        sa.Column("lsoa_code", sa.String(length=9), nullable=False),
        sa.Column("lsoa_name", sa.String(length=100), nullable=False),
        sa.Column("msoa_code", sa.String(length=9), nullable=False),
        sa.Column("msoa_name", sa.String(length=100), nullable=False),
        sa.Column("lad_code", sa.String(length=9), nullable=False),
        sa.Column("lad_name", sa.String(length=100), nullable=False),
        sa.Column("region_code", sa.String(length=9), nullable=True),
        sa.Column("region_name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("lsoa_code", name=op.f("pk_geo_lookup")),
    )
    op.create_index("ix_geo_lookup_lad_code", "geo_lookup", ["lad_code"], unique=False)
    op.create_index("ix_geo_lookup_msoa_code", "geo_lookup", ["msoa_code"], unique=False)
    op.create_table(
        "indicator",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("indicator_id", sa.String(length=100), nullable=False),
        sa.Column("indicator_name", sa.String(length=255), nullable=False),
        sa.Column("lad_code", sa.String(length=9), nullable=False),
        sa.Column("lad_name", sa.String(length=100), nullable=False),
        sa.Column("reference_period", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("dataset_code", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicator")),
    )
    op.create_index(
        "ix_indicator_upsert_key",
        "indicator",
        ["indicator_id", "lad_code", "reference_period"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_indicator_upsert_key", table_name="indicator")
    op.drop_table("indicator")
    op.drop_index("ix_geo_lookup_msoa_code", table_name="geo_lookup")
    op.drop_index("ix_geo_lookup_lad_code", table_name="geo_lookup")
    op.drop_table("geo_lookup")
    op.drop_table("dataset_metadata")
    # ### end Alembic commands ###
